# Generated by Django 4.1.2 on 2022-10-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='star',
            new_name='stars',
        ),
    ]
