# Generated by Django 4.1.2 on 2022-11-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True, verbose_name=(('white', 'White Chocolate'), ('dark', 'Dark Chocolate'), ('nut', 'Nuts Chocolate')))),
                ('cover', models.ImageField(blank=True, upload_to='category/category_cover')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
