# Generated by Django 4.1.2 on 2022-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('White Chocolate', 'White Chocolate'), ('Dark Chocolate', 'Dark Chocolate'), ('Nuts Chocolate', 'Nuts Chocolate')], max_length=30, null=True),
        ),
    ]
